### ISSUE TITLE
请问这个模块能单独使用吗，为什么安装以后报个错误？

### ISSUE THREAD

**Issue by zlycong** [JoneXiong/weodoo#1]
File "E:\odoo\odoo\addons\base\ir\ir_model.py", line 1028, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: weodoo.provider_third

**Comment by JoneXiong** [comment]
就是单独使用的，确认下你的模块目录名是否为weodoo 不能随便改的 @zlycong
